import type { Metadata } from "next";
import { Lora, Montserrat } from "next/font/google";
import "./globals.css";
import NavMenu from "@/components/NavMenu";
import Footer from "@/components/Footer";
import CartFixed from "@/components/CartFixed";

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s | TajaClean",
    default: "Dobrodošli | TajaClean",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="sl"
      className={`${lora.variable} ${montserrat.variable} scroll-smooth`}
      data-scroll-behavior="smooth"
    >
      <body className="font-montserrat text-neutral1 mx-4 max-w-[1440px] md:mx-8 lg:mx-20 xl:mx-auto xl:px-20">
        <NavMenu />
        {children}
        <CartFixed />
        <Footer />
      </body>
    </html>
  );
}
